export const listingsQuery = `*[_type == "listing"] | order(featured desc, title asc) {
  _id,
  title,
  "slug": slug.current,
  shortDescription,
  featured,
  heroImage,
  gallery,
  body,
  lengthM,
  beamM,
  clearanceM,
  depthM,
  powerSupply,
  locationLabel,
  address,
  lat,
  lng,
  waterwayNote,
  metaTitle,
  metaDescription
}`;

export const listingBySlugQuery = `*[_type == "listing" && slug.current == $slug][0] {
  _id,
  title,
  "slug": slug.current,
  shortDescription,
  featured,
  heroImage,
  gallery,
  body,
  lengthM,
  beamM,
  clearanceM,
  depthM,
  powerSupply,
  locationLabel,
  address,
  lat,
  lng,
  waterwayNote,
  metaTitle,
  metaDescription
}`;

export const featuredListingsQuery = `*[_type == "listing" && featured == true] | order(title asc) [0...6] {
  _id,
  title,
  "slug": slug.current,
  shortDescription,
  featured,
  heroImage,
  gallery,
  lengthM,
  beamM,
  clearanceM,
  depthM,
  powerSupply,
  locationLabel,
  address,
  lat,
  lng,
  waterwayNote
}`;
